- app/build.gradle
- app/src/main/java/ai/elimu/content_provider/rest/ImagesService.java
- app/src/main/java/ai/elimu/content_provider/rest/StoryBooksService.java
- app/src/main/java/ai/elimu/content_provider/room/GsonToRoomConverter.java
- app/src/main/java/ai/elimu/content_provider/ui/image/ImagesFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/storybook/StoryBooksFragment.java
> #4 Download Images from REST API (v2)

- app/schemas/ai.elimu.content_provider.room.db.RoomDb/6.json
- app/src/main/java/ai/elimu/content_provider/room/GsonToRoomConverter.java
- app/src/main/java/ai/elimu/content_provider/room/dao/StoryBookChapterDao.java
- app/src/main/java/ai/elimu/content_provider/room/db/RoomDb.java
- app/src/main/java/ai/elimu/content_provider/room/entity/StoryBookChapter.java
- app/src/main/java/ai/elimu/content_provider/ui/storybook/StoryBooksFragment.java
> #1 Download StoryBooks from REST API (v2)

- app/build.gradle
- app/schemas/ai.elimu.content_provider.room.db.RoomDb/13.json
- app/src/main/java/ai/elimu/content_provider/room/GsonToRoomConverter.java
- app/src/main/java/ai/elimu/content_provider/room/db/RoomDb.java
- app/src/main/java/ai/elimu/content_provider/room/entity/Content.java
- Added `usageCount` to Content entity
> #12 Add usageCount to Word

- app/build.gradle
- app/schemas/ai.elimu.content_provider.room.db.RoomDb/14.json
- app/src/main/java/ai/elimu/content_provider/room/dao/Image_WordDao.java
- app/src/main/java/ai/elimu/content_provider/room/db/RoomDb.java
- app/src/main/java/ai/elimu/content_provider/room/entity/Image_Word.java
- app/src/main/java/ai/elimu/content_provider/ui/image/ImagesFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/storybook/StoryBooksFragment.java
> #21 Add content labels

- app/schemas/ai.elimu.content_provider.room.db.RoomDb/17.json
- app/src/main/java/ai/elimu/content_provider/room/GsonToRoomConverter.java
- app/src/main/java/ai/elimu/content_provider/room/dao/StoryBookDao.java
- app/src/main/java/ai/elimu/content_provider/room/db/Converters.java
- app/src/main/java/ai/elimu/content_provider/room/db/RoomDb.java
- app/src/main/java/ai/elimu/content_provider/room/entity/StoryBook.java
This will change the way the storybooks are sorted in the Vitabu app.
- Add `ReadingLevel` to Room entity
> #44 Sort StoryBooks by readingLevel, title

- app/src/main/java/ai/elimu/content_provider/util/FileHelper.java
- Change the storage location from `lang<LANG>/images/` to `/Pictures`
> refactor: #63 Provide Image file to other apps

- app/src/main/java/ai/elimu/content_provider/ui/allophone/AllophonesFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/audio/AudiosFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/emoji/EmojisFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/image/ImagesFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/letter/LettersFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/number/NumbersFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/storybook/StoryBooksFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/video/VideosFragment.java
- app/src/main/java/ai/elimu/content_provider/ui/word/WordsFragment.java
- app/src/main/res/values/colors.xml
> feat: #84 Display error message when HTTP response is not successful

- .github/workflows/gradle-build.yml
- .github/workflows/gradle-release.yml
- README.md
- app/build.gradle
- build.gradle
- utils/build.gradle
- utils/src/main/java/ai/elimu/content_provider/utils/ContentProviderUtil.java
> chore: Upgrade to model-2.0.62

- app/build.gradle
- utils/build.gradle
> Upgrade to model-2.0.66

- app/schemas/ai.elimu.content_provider.room.db.RoomDb/25.json
- app/schemas/ai.elimu.content_provider.room.db.RoomDb/26.json
- app/src/main/java/ai/elimu/content_provider/provider/LetterContentProvider.java
- app/src/main/java/ai/elimu/content_provider/provider/SoundContentProvider.java
- app/src/main/java/ai/elimu/content_provider/room/GsonToRoomConverter.java
- app/src/main/java/ai/elimu/content_provider/room/dao/LetterDao.java
- app/src/main/java/ai/elimu/content_provider/room/dao/LetterSound_LetterDao.java
- app/src/main/java/ai/elimu/content_provider/room/dao/LetterSound_SoundDao.java
- app/src/main/java/ai/elimu/content_provider/room/dao/SoundDao.java
- app/src/main/java/ai/elimu/content_provider/room/db/RoomDb.java
- app/src/main/java/ai/elimu/content_provider/room/entity/LetterSound_Letter.java
- app/src/main/java/ai/elimu/content_provider/room/entity/LetterSound_Sound.java
- app/src/main/java/ai/elimu/content_provider/ui/letter_sound/LetterSoundsFragment.java
- utils/src/main/java/ai/elimu/content_provider/utils/ContentProviderUtil.java
- utils/src/main/java/ai/elimu/content_provider/utils/converter/CursorToLetterSoundGsonConverter.java
- utils/src/main/java/ai/elimu/content_provider/utils/converter/CursorToSoundGsonConverter.java
> Download letter-sound correspondence letters from REST API

- app/build.gradle
- utils/build.gradle
> chore(deps): model-2.0.80

- README.md
> docs: snapshot versions

- app/src/main/java/ai/elimu/content_provider/ui/video/VideosFragment.kt
Replace deprecated `getColor()` API usages
> Replace deprecated `getColor()` API usages

- app/src/main/java/ai/elimu/content_provider/util/MultimediaDownloader.kt
- Extract log tag to a constant value
- Remove redundant initializer
> Extract log tag to a constant value

- app/src/main/java/ai/elimu/content_provider/provider/VideoContentProvider.kt
Replace String concatenation with template
> Replace String concatenation with template

- app/src/main/java/ai/elimu/content_provider/provider/EmojiContentProvider.kt
Fix Lint warnings in EmojiContentProvider
> Fix Lint warnings in EmojiContentProvider

- app/src/main/java/ai/elimu/content_provider/provider/LetterContentProvider.kt
Fix Lint warnings in LetterContentProvider
> Fix Lint warnings in LetterContentProvider

- app/src/main/java/ai/elimu/content_provider/room/db/Converters.java
Remove redundant local variables
> Remove redundant local variables

- app/src/main/java/ai/elimu/content_provider/room/db/Converters.java
Update Converters class document reference link
> Update Converters class document reference link

- app/src/main/res/drawable/ic_menu_audiotrack.xml
- app/src/main/res/values/strings.xml
> Remove unused icon/strings

- .github/workflows/gradle-release.yml
> release: increase timeout during apk publishing

- gradle/libs.versions.toml
https://github.com/elimu-ai/appstore/releases/tag/2.5.73
* Resolves #
* 
* 
*
*
> chore(deps): appstore 2.5.73
